In [ ]:
# NEW WRITE XYZ
#def writexyz_generalized(path,instance_class,number_files):
def writexyz_generalized(path,instance_class,number):
    '''
    simple xyz writing, with atomic symbols/x/y/z and no other information sometimes misunderstood by some utilities, such as DebyeCalculator
    input : 
            - path : path in which the xyz files are created
            - instance_class: instance of the class used
    '''
    # verify if the path does exist
    if not os.path.isdir(path):
        raise FileNotFoundError(f"Directory '{path}'does not exist.")

    # extract attributes from the class to write the dictionnary and the name of the file
    if isinstance(instance_class,object):
        print('Entry is instance of class')
        metadata = instance_class.__dict__.copy() # Get all attributes
        element=instance_class.element
        crystalStructure= instance_class.crystalStructure 
        shape= instance_class.__class__.__name__ 
        size= instance_class.size #angs !!!!
        NP=instance_class.NP
        element_array=NP.get_chemical_symbols()
        MOI=self.moi #amu.angs²
        MOI_normalized=self.MOI_size  #angs²
        number_atoms=instance_class.nAtoms
        radius1=self.radiusCircumscribedSphere #angs
        radius2=self.radiusInscribedSphere #angs
        composition={}
        
        for elements in element_array:
            if elements in composition:
                composition[elements]+=1
            else:
                composition[elements]=1

    
    coord=NP.get_positions()
    natoms=len(element_array) 
    #write the filename
    filename= f"{element}_{crystalStructure}_{"{:07d}".format(number)}_.xyz"
    full_path = os.path.join(path, filename)
    print('full_path:',full_path)
    print('NP:',NP)
    line2write='%d \n'%natoms
    dictionnary=dict([('composition', composition), ('crystal structure',crystalStructure), ('shape', shape ), ('MOI', MOI ),('MOI', MOI_normalized),])
    line2write+='%s \n'%dictionnary
    #print('line2write=',line2write)
    
    # writing of the coordinates
    for i in range(natoms):
        line2write+='%s'%str(element_array[i])+'\t %.8f'%float(coord[i,0])+'\t %.8f'%float(coord[i,1])+'\t %.8f'%float(coord[i,2])+'\n'
    with open(full_path,'w') as file:
        file.write(line2write)

In [22]:
number = 100211
print("{:07d}".format(number))
print(range(number))
print(len([0,1,2]))

0100211
range(0, 100211)
3


In [10]:
a=[1,2,3]
b=max(a)
print(b)

3


In [19]:
size=[10,20,30,89,65,23,56,12,56,123]



for i in size :
    number=size.index(i)+1
    print(number)

1
2
3
4
5
6
7
8
7
10


In [21]:
import numpy as np
size=np.linspace(1, 10, num=5)
print(size)

[ 1.    3.25  5.5   7.75 10.  ]


In [28]:
import numpy as np
size=np.linspace(1, 5, num=5)




for i in size :
    number=int(size.np.index(i)+1)
    print(number)

(array([0]),)
(array([0]),)
(array([0]),)
(array([0]),)
(array([0]),)


/tmp/ipykernel_207669/85571521.py:9: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  number=np.where(i)


In [30]:
import numpy as np
size=np.linspace(1, 5, num=5)



for i in size :
    number= int(np.where(size == i)[0][0] + 1)  
    print(number)

1
2
3
4
5


In [31]:
print('Objet isn''t'' a class instance')

Objet isnt a class instance
